name: covid_ITA_IIS
channels:
  - defaults
dependencies:
  - pandas=1.2.4
  - numpy=1.20.1
  - ipywidgets=7.5.1
  - tqdm=4.45.0
  - matplotlib=3.2.2
  - jupyter=1.0.0
  - xgboost=1.3.3
  - pip:
    - shap==0.35.0
    - voila==0.2.4

